name: Betopia Website CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    defaults:
      run:
        working-directory: /home/betopia/betopia-runner/_work/betopia-website/betopia-website

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js project
        run: yarn build

      - name: Restart project with PM2
        run: |
          if pm2 describe website > /dev/null; then
            pm2 restart website --update-env
          else
            pm2 start "yarn start" --name website
          fi

      - name: Save PM2 process list
        run: pm2 save
