name: Betopia Staging Website CI/CD
on:
  push:
    branches: ["staging"]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: "206.162.244.163"
        username: "root"
        password: "DufiJAPpyz7xIyGgvDVx"
        port: "22"
        script: "cd /var/www/betopia-website && ./.script/staging.sh"
